### ISSUE TITLE
Suggest things that should be fixed in Team section

### ISSUE THREAD

**Issue by RKC3000** [dscbkbiet/dscbkbiet.github.io#20]
Once check the Team section and tell me here what are the changes needed.

Just ignore the optimization of cards at different sizes.

**Comment by soyo-kaze** [comment]
Issues:
* Reduce gap between image and info in card.
* Try to increase size of profile pics on hover. (like a small zoom effect i.e. size increase by 5px-10px.)
* Remove horizontal scroll bar (Issue in MuiGrid or the Grid system you are using.)
* "The Team" needs some styling.

@RKC3000

**Comment by shekharAggarwal** [comment]
- Make hover effect permanent background on image
@RKC3000

**Comment by RKC3000** [comment]
OK got it

I will try to fix them as soon as possible.
