### ISSUE TITLE
Remove "Powered by Google" violates GDSC guidelines!! 

### ISSUE THREAD

**Issue by soyo-kaze** [dscbkbiet/dscbkbiet.github.io#8]
https://github.com/dscbkbiet/dscbkbiet.github.io/blob/3ae7445ffce89ff3301aa905b053ef48d5e2e964/src/components/Home.js#L32

Remove `Powered by Google` violates GDSC guidelines!!

**Comment by aniketkumarsinha** [comment]
Done
